[package]
name = "voodoo"
version = "0.0.1"
authors = ["Nick Sanders <cogciprocate@gmail.com>"]
description = "A high-level Vulkan API"
# documentation = "https://doc.cogciprocate.com/vkc"
homepage = "https://github.com/cogciprocate/voodoo"
repository = "https://github.com/cogciprocate/voodoo"
readme = "README.md"
# keywords = ["vulkan", "gpu", "gpgpu", "async"]
license = "MIT/Apache-2.0"
exclude = ["target/*", "*.png", "bak/*"]

[dependencies]
# vkc = "0.0.1"
# vkc = { git = "https://github.com/cogciprocate/vlc" }
# vkc = { path = "../vkc" }